package modelo;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Alquiler de Autos
//  @ File Name : ReservaDTO.java
//  @ Date : 09/05/2013
//  @ Author : Grupo 5
//
//

public class ReservaDTO {
	private int nroReserva;
	private String estado;
	private Date fechaInicio;
	private Date fechaFin;
	private String marca;
	private String modelo;
	private String tipo;
	private float costo;
	private int dniCliente;
	private String nombreCliente;
	private String apellidoCliente;

	public ReservaDTO(int nroReserva, String estado, Date fechaInicio,
			Date fechaFin, String marca, String modelo, String tipo,
			float costo, int dni, String nombre, String apellido) {
		this.nroReserva = nroReserva;
		this.estado = estado;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.marca = marca;
		this.modelo = modelo;
		this.tipo = tipo;
		this.costo = costo;
		dniCliente = dni;
		nombreCliente = nombre;
		apellidoCliente = apellido;
	}

	public String getTipo() {
		return tipo;
	}

	public void setNroReserva(int nroReserva) {
		this.nroReserva = nroReserva;
	}

	public int getNroReserva() {
		return nroReserva;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getEstado() {
		return estado;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Date getFechaFin() {
		return fechaFin;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getMarca() {
		return marca;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getModelo() {
		return modelo;
	}

	public void setCosto(float costo) {
		this.costo = costo;
	}

	public float getCosto() {
		return costo;
	}

	public void setDniCliente(int dniCliente) {
		this.dniCliente = dniCliente;
	}

	public int getDniCliente() {
		return dniCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	public String getNombreCliente() {
		return nombreCliente;
	}

	public void setApellidoCliente(String apellidoCliente) {
		this.apellidoCliente = apellidoCliente;
	}

	public String getApellidoCliente() {
		return apellidoCliente;
	}
}