package modelo;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Alquiler de Autos
//  @ File Name : Reserva.java
//  @ Date : 09/05/2013
//  @ Author : Grupo 5
//
//

public class Reserva {
	private static int ultNroReserva;
	private int nroReserva;
	private String estado;
	private Date fechaInicio;
	private Date fechaFin;
	private Modelo modelo;
	private Cliente cliente;

	public Boolean esMiCliente(int dni) {
		if (cliente.getDni() == dni)
			return true;
		return false;
	}

	public ReservaDTO crearReservaDTO() {
		return new ReservaDTO(nroReserva, estado, fechaInicio, fechaFin,
				modelo.getMarca(), modelo.getModelo(), modelo.getTipo(),
				modelo.calcularCosto(fechaInicio, fechaFin, null),
				cliente.getDni(), cliente.getNombre(), cliente.getApellido());
	}

	public Reserva(Date fechaInicio, Date fechaFin, Modelo mod, Cliente cli) {
		nroReserva = generarNroReserva();
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.modelo = mod;
		this.cliente = cli;
	}
	
	public boolean sosReserva(int nroreserva){
		return nroreserva==this.nroReserva;
	}

	public int getNroReserva() {
		return nroReserva;
	}

	public static int generarNroReserva() {
		return ++ultNroReserva;
	}

	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fecha) {
		fechaInicio = fecha;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String newEst) {
		estado = newEst;
	}

	public Date getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(Date fecha) {
		fechaFin = fecha;
	}

	public Modelo getModelo() {
		return modelo;
	}

	public void setModelo(Modelo mod) {
		modelo = mod;
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cli) {
		cliente = cli;
	}
}