package modelo;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Alquiler de Autos
//  @ File Name : Alquiler.java
//  @ Date : 09/05/2013
//  @ Author : Grupo 5
//
//

public class Alquiler {
	private static int proxNroAlquiler;
	private int nroAlquiler;
	private Date fechaInicio;
	private Date fechaFin;
	private Date fechaDevolucion;
	private String observacionesCliente;
	private String observacionesDevolucion;
	private float descuento;
	private float recargo;
	private Modelo modelo;
	private Cliente cliente;
	private Automovil automovil;

	public float calcularTotal() {
		return (modelo.calcularCosto(fechaInicio, fechaFin, fechaDevolucion)
				- descuento + recargo);
	}

	public AlquilerDTO crearAlquilerDTO() {
		return new AlquilerDTO(nroAlquiler, modelo.calcularCosto(fechaInicio,
				fechaFin, fechaDevolucion), cliente.getDni(),
				cliente.getNombre(), cliente.getApellido(), fechaInicio,
				fechaFin, fechaDevolucion, observacionesCliente,
				observacionesDevolucion, modelo.getTipo());
	}

	public Alquiler(Date fechaInicio, Date fechaFin, Modelo modelo,
			Cliente cliente) {
		nroAlquiler = generarNroAlquiler();
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.modelo = modelo;
		this.cliente = cliente;
	}

	private static int generarNroAlquiler() {
		return ++proxNroAlquiler;
	}

	public int getNroAlquiler() {
		return nroAlquiler;
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cli) {
		cliente = cli;
	}

	public Automovil getAutomovil() {
		return automovil;
	}

	public void setAutomovil(Automovil auto) {
		automovil = auto;
	}

	public Modelo getModelo() {
		return modelo;
	}

	public void setModelo(Modelo mod) {
		modelo = mod;
	}

	public String getObservacionesCliente() {
		return observacionesCliente;
	}

	public void setObservacionesCliente(String obs) {
		observacionesCliente = obs;
	}

	public String getObservacionesDevolucion() {
		return observacionesDevolucion;
	}

	public void setObservacionesDevolucion(String obs) {
		observacionesDevolucion = obs;
	}

	public float getDescuento() {
		return descuento;
	}

	public void setDescuento(float descto) {
		descuento = descto;
	}

	public float getRecargo() {
		return recargo;
	}

	public void setRecargo(float rec) {
		recargo = rec;
	}

	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fecha) {
		fechaInicio = fecha;
	}

	public Date getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(Date fecha) {
		fechaFin = fecha;
	}

	public Date getFechaDevolucion() {
		return fechaDevolucion;
	}

	public void setFechaDevolucion(Date fecha) {
		fechaDevolucion = fecha;
	}

	public void finalizarAlquiler(Date fechaDevolucion, String observ,
			float kilometraje, float combustible, float descuento, float recargo) {
		this.fechaDevolucion = fechaDevolucion;
		automovil.setKilometraje(kilometraje);
		automovil.setCombustible(combustible);
		observacionesDevolucion = observ;
		this.descuento = descuento;
		this.recargo = recargo;
		automovil.quitarFechaOcupado(fechaInicio, fechaFin);
	}
	
	public boolean sosDelCliente(int dni){
		return cliente.sosCliente(dni);
	}
	
	public boolean sosAlquiler(int nroAlq){
		return nroAlq==this.nroAlquiler;
	}
	
}