package modelo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Practica Final
//  @ File Name : Contratado.java
//  @ Date : 14/07/2013
//  @ Author : Sebastian Szarfsztejn
//
//

public class Contratado extends Empleado {
	private float valorHora;
	private int horasContratadas;

	public float calcularSueldo() {
		return valorHora * horasContratadas;
	}

	public Contratado(String nom, String dom, int leg, float valHora, int horas) {
		super(nom, dom, leg);
		valorHora = valHora;
		horasContratadas = horas;
	}
}