package modelo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Practica Final
//  @ File Name : EmpleadoView.java
//  @ Date : 14/07/2013
//  @ Author : Sebastian Szarfsztejn
//
//

public class EmpleadoView {
	private String nombre;
	private String domicilio;
	private int legajo;

	public EmpleadoView(String nombre, String domicilio, int legajo) {
		this.nombre = nombre;
		this.domicilio = domicilio;
		this.legajo = legajo;
	}

	public String getNombre() {
		return nombre;
	}
	public String getDomicilio() {
		return domicilio;
	}
	public int getLegajo() {
		return legajo;
	}
}