package modelo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Practica Final
//  @ File Name : Sueldo.java
//  @ Date : 14/07/2013
//  @ Author : Sebastian Szarfsztejn
//
//

public class Sueldo {
	private String mes;
	private Empleado empleado;
	private float sueldoAPagar;

	public Sueldo(String mes, Empleado emp) {
		this.mes = mes;
		empleado = emp;
		sueldoAPagar = emp.calcularSueldo();
	}

	public boolean sosElSueldo(int legajo, String mes) {
		return empleado.sosElEmpleado(legajo) && this.mes.equals(mes);
	}

	public SueldoView getView() {
		return new SueldoView(mes, empleado.getView(), sueldoAPagar);
	}

	public String getMes() {
		return mes;
	}

	public Empleado getEmpleado() {
		return empleado;
	}

	public float getSueldoAPagar() {
		return sueldoAPagar;
	}
}