package modelo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Practica Final
//  @ File Name : SueldoView.java
//  @ Date : 14/07/2013
//  @ Author : Sebastian Szarfsztejn
//
//

public class SueldoView {
	private String mes;
	private EmpleadoView empleado;
	private float sueldoAPagar;

	public SueldoView(String mes, EmpleadoView emp, float sueldo) {
		this.mes = mes;
		empleado = emp;
		sueldoAPagar = sueldo;
	}

	public String getMes() {
		return mes;
	}

	public EmpleadoView getEmpleado() {
		return empleado;
	}

	public float getSueldoAPagar() {
		return sueldoAPagar;
	}
}