package modelo;

import java.util.Date;
import java.util.Vector;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Tran de Autos
//  @ File Name : FacturaDTO.java
//  @ Date : 09/05/2013
//  @ Author : Grupo 5
//
//

public class FacturaDTO {
	private int nroFactura;
	private Date fecha;
	private float impTotal;
	private String tipo;
	private int nroTran;
	private int dni;
	private String nombre;
	private String apellido;
	private Vector<ItemFacturaDTO> items;

	public FacturaDTO(int nroFactura, Date fecha, float impTotal, String tipo,
			int nroTran, int dni, String nombre, String apellido) {
		this.nroFactura = nroFactura;
		this.fecha = fecha;
		this.impTotal = impTotal;
		this.tipo = tipo;
		this.nroTran = nroTran;
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.items = new Vector<ItemFacturaDTO>();
	}

	public int getNroFactura() {
		return nroFactura;
	}

	public void setNroFactura(int nroFactura) {
		this.nroFactura = nroFactura;
	}

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public float getImpTotal() {
		return impTotal;
	}

	public void setImpTotal(float impTotal) {
		this.impTotal = impTotal;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public int getNroTran() {
		return nroTran;
	}

	public void setNroTran(int nroTran) {
		this.nroTran = nroTran;
	}

	public int getDni() {
		return dni;
	}

	public void setDni(int dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public void agregarItem(String descripcion, float monto) {
		ItemFacturaDTO it = new ItemFacturaDTO(descripcion, monto);
		items.add(it);
	}

	public Vector<ItemFacturaDTO> getItems() {
		return items;
	}
}