package modelo;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Alquiler de Autos
//  @ File Name : AlquilerDTO.java
//  @ Date : 09/05/2013
//  @ Author : Grupo 5
//
//

public class AlquilerDTO {
	private float costo;
	private int nroAlquiler;
	private int dniCliente;
	private String nombreCliente;
	private String apellidoCliente;
	private Date fechaInicio;
	private Date fechaFin;
	private Date fechaDevolucion;
	private String observacionesCliente;
	private String observacionesDevolucion;
	private String tipo;

	public AlquilerDTO(int nroAlquiler, float costo, int dniCliente,
			String nombreCliente, String apellidoCliente, Date fechaInicio,
			Date fechaFin, Date fechaDevolucion, String obsCli, String obsDev,
			String tipo) {
		this.costo = costo;
		this.nroAlquiler = nroAlquiler;
		this.dniCliente = dniCliente;
		this.nombreCliente = nombreCliente;
		this.apellidoCliente = apellidoCliente;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.fechaDevolucion = fechaDevolucion;
		observacionesCliente = obsCli;
		observacionesDevolucion = obsDev;
		this.tipo = tipo;
	}

	public float getCosto() {
		return costo;
	}

	public void setCosto(float costo) {
		this.costo = costo;
	}

	public int getNroAlquiler() {
		return nroAlquiler;
	}

	public void setNroAlquiler(int nroAlquiler) {
		this.nroAlquiler = nroAlquiler;
	}

	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getObservacionesCliente() {
		return observacionesCliente;
	}

	public void setObservacionesCliente(String observacionesCliente) {
		this.observacionesCliente = observacionesCliente;
	}

	public int getDniCliente() {
		return dniCliente;
	}

	public String getNombreCliente() {
		return nombreCliente;
	}

	public String getApellidoCliente() {
		return apellidoCliente;
	}

	public Date getFechaDevolucion() {
		return fechaDevolucion;
	}

	public String getObservacionesDevolucion() {
		return observacionesDevolucion;
	}

	public String getTipo() {
		return tipo;
	}
}