package modelo;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Alquiler de Autos
//  @ File Name : ClienteDTO.java
//  @ Date : 09/05/2013
//  @ Author : Grupo 5
//
//

public class ClienteDTO {
	private int dni;
	private Date fechaNac;
	private String nombre;
	private String apellido;
	private String telefono;
	private String domicilio;
	private String sexo;
	private String nacionalidad;
	private String username;
	private String password;
	private boolean activo;

	public ClienteDTO(int dni, Date fechaNac, String nom, String ape,
			String tel, String domicilio, String sex, String nacionalidad,
			String usr, String pass, boolean activo) {
		this.dni = dni;
		this.fechaNac = fechaNac;
		nombre = nom;
		apellido = ape;
		telefono = tel;
		this.domicilio = domicilio;
		sexo = sex;
		this.nacionalidad = nacionalidad;
		username = usr;
		password = pass;
		this.activo = activo;
	}

	public int getDni() {
		return dni;
	}

	public void setDni(int dni) {
		this.dni = dni;
	}

	public Date getFechaNac() {
		return fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDomicilio() {
		return domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getSexo() {
		return sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getNacionalidad() {
		return nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isActivo() {
		return activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}
}