package modelo;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Alquiler de Autos
//  @ File Name : Cliente.java
//  @ Date : 09/05/2013
//  @ Author : Grupo 5
//
//

public class Cliente {
	private int dni;
	private Date fechaNac;
	private String nombre;
	private String apellido;
	private String telefono;
	private String domicilio;
	private String sexo;
	private String nacionalidad;
	private String username;
	private String password;
	private boolean activo;

	public boolean sosCliente(int dni, String usr) {
		if (this.dni == dni || this.username == usr) {
			return true;
		}
		return false;
	}

	public boolean sosCliente(int dni) {
		if (this.dni == dni) {
			return true;
		}
		return false;
	}

	public ClienteDTO crearClienteDTO() {
		return new ClienteDTO(dni, fechaNac, nombre, apellido, telefono,
				domicilio, sexo, nacionalidad, username, password, activo);
	}

	public Cliente(int dni, String nom, String ape, Date fechaNac,
			String domicilio, String sex, String nacionalidad, String tel,
			String usr, String pass) {
		this.dni = dni;
		this.fechaNac = fechaNac;
		nombre = nom;
		apellido = ape;
		telefono = tel;
		this.domicilio = domicilio;
		sexo = sex;
		this.nacionalidad = nacionalidad;
		username = usr;
		password = pass;
		activo = true;
	}

	public Cliente(int dni, String nom, String ape, Date fechaNac,
			String domicilio, String sex, String nacionalidad, String tel) {
		this.dni = dni;
		this.fechaNac = fechaNac;
		nombre = nom;
		apellido = ape;
		telefono = tel;
		this.domicilio = domicilio;
		sexo = sex;
		this.nacionalidad = nacionalidad;
		activo = true;
	}
	
	public void modificarDatos(String nombre, String ape, Date fechaNacimiento, String domicilio, String sex, String nacionalidad, String pass, String tel){
		this.setNombre(nombre);
		this.setApellido(ape);
		this.setFechaNac(fechaNacimiento);
		this.setDomicilio(domicilio);
		this.setSexo(sex);
		this.setNacionalidad(nacionalidad);
		this.setPassword(pass);
		this.setTelefono(tel);
	}

	public boolean isActivo() {
		return activo;
	}

	public void setActivo(boolean estado) {
		activo = estado;
	}

	public int getDni() {
		return dni;
	}

	public void setActivo(int dni) {
		this.dni = dni;
	}

	public Date getFechaNac() {
		return fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDomicilio() {
		return domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getSexo() {
		return sexo;
	}

	public void setSexo(String sex) {
		sexo = sex;
	}

	public String getNacionalidad() {
		return nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String usr) {
		username = usr;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String pwd) {
		password = pwd;
	}
}